name: sirius
description: "Stop Learning Start understanding"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_sign_in: ^5.4.2
  fluentui_icons: ^1.0.0
  image_picker: ^1.0.4
  flutter_markdown: ^0.7.3
  flutter_math_fork: ^0.7.1
  animated_text_kit: ^4.2.2
  http: ^0.13.6
  permission_handler: ^11.3.0
  video_player: ^2.7.0
  chewie: ^1.7.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.13.5
  firebase_storage: ^11.6.5
  firebase_messaging: ^14.7.10
  flutter_staggered_animations: ^1.1.1
  shared_preferences: ^2.2.2
  intl: 0.20.2
  provider: ^6.1.2
  lottie: ^3.0.0
  razorpay_flutter: ^1.4.0
  url_launcher: ^6.2.5
  flutter_localizations:
    sdk: flutter
  flutter_slidable: ^3.0.0
  confetti: ^0.7.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#1E1E2D"
  adaptive_icon_foreground: "assets/images/logo.png"

flutter:
  uses-material-design: true

  generate: true   # ✅ Required for localization code generation

  assets:
    - assets/images/logo.png
    - assets/images/google.png
    - assets/images/empty_folder.png
    - assets/images/CourseMsg.png
    - assets/animation/Delete animation json.json
